### ISSUE TITLE
KiwiCommandError: chroot: stderr: groupadd: group 'wheel' already exists

### ISSUE THREAD

**Issue by itsalasdair** [SUSE/kiwi-descriptions#91] opened 2022-02-08 08:49 UTC
Hi there,

I am building a new JeOS image for 15.3* and when running my 15.2 config.sh and config.xml with the `kiwi-ng --profile Disk --type oem system build --description /path/used/ --target-dir /path/to` command, I get an error:

```
KiwiCommandError: chroot: stderr: groupadd: group 'wheel' already exists
```

... I saw that something similar to this has been posted previously however the information link given does not work (https://github.com/OSInside/kiwi-descriptions/issues/40) 

I do not have anything as such configured in the .sh and .xml, other than a few bits, but nothing to do with the 'group' wheel

* I assume I am doing this right - we had a 15.2 image and am needing to make a fresh 15.3 image. I am under the impression it's just a case of re-building the image again without any real changes needed?

**Comment by itsalasdair** [comment] 2022-02-08 08:52
These are the packages I am installing with the .xml file:

(I have tried with removing the group(wheel) package too)

```
<package name="aaa_base-extras"/>
<package name="acl"/>
<package name="bash-completion"/>
<package name="checkmedia"/>
<package name="chromium"/>
<package name="chrony"/>
<package name="curl"/>
<package name="dhcp-client"/>
<package name="dolphin"/>
<package name="dosfstools"/>
<package name="dracut"/>
<package name="fipscheck"/>
<package name="firewalld"/>
<package name="fontconfig"/>
<package name="fonts-config"/>
<package name="gcc"/>
<package name="grep"/>
<package name="group(mail)"/>
<package name="group(wheel)"/>
<package name="grub2"/>
<package name="grub2-arm64-efi" arch="aarch64"/>
<package name="grub2-branding-openSUSE" bootinclude="true"/>
<package name="grub2-i386-pc"/>
<package name="grub2-systemd-sleep-plugin"/>
<package name="grub2-x86_64-efi" arch="x86_64"/>
<package name="haveged"/>
<package name="htop"/>
<package name="icedtea-web"/>
<package name="ifplugd"/>
<package name="iproute2"/>
<package name="iputils"/>
<package name="issue-generator"/>
<package name="java-11-openjdk"/>
<package name="kate"/>
<package name="kernel-default"/>
<package name="konsole"/>
<package name="less"/>
<package name="live-add-yast-repos"/>
<package name="lsof"/>
<package name="lvm2"/>
<package name="nano"/>
<package name="NetworkManager"/>
<package name="NetworkManager-branding-openSUSE"/>
<package name="nmap"/>
<package name="openssh"/>
<package name="openSUSE-build-key"/>
<package name="open-vm-tools"/>
<package name="open-vm-tools-desktop"/>
<package name="parted"/>
<package name="patterns-base-base"/>
<package name="patterns-base-enhanced_base"/>
<package name="patterns-base-minimal_base"/>
<package name="patterns-base-x11"/>
<package name="patterns-base-x11_enhanced"/>
<package name="patterns-fonts-fonts"/>
<package name="patterns-kde-kde_plasma"/>
<package name="patterns-openSUSE-base"/>
<package name="patterns-yast-x11_yast"/>
<package name="patterns-yast-yast2_basis"/>
<package name="plymouth"/>
<package name="plymouth-dracut"/>
<package name="plymouth-theme-bgrt"/>
<package name="remmina"/>
<package name="remmina-plugin-rdp"/>
<package name="remmina-plugin-vnc"/>
<package name="rsync"/>
<package name="salt-minion"/>
<package name="sddm-branding-openSUSE"/>
<package name="sddm-theme-openSUSE"/>
<package name="shim" arch="x86_64"/>
<package name="sudo"/>
<package name="syslinux"/>
<package name="systemd"/>
<package name="systemd-logger"/>
<package name="systemd-sysvinit"/>
<package name="tar"/>
<package name="telnet"/>
<package name="timezone"/>
<package name="vim"/>
<package name="wget"/>
<package name="which"/>
<package name="wicked"/>
<package name="xorg-x11"/>
<package name="xorg-scripts"/>
<package name="xorg-x11-Xvnc"/>
<package name="xorg-x11-Xvnc-java"/>
<package name="xorg-x11-Xvnc-module"/>
<package name="xorg-x11-Xvnc-novnc"/>
<package name="xorg-x11-devel"/>
<package name="xorg-x11-driver-input"/>
<package name="xorg-x11-driver-video"/>
<package name="xorg-x11-essentials"/>
<package name="xorg-x11-fonts"/>
<package name="xorg-x11-fonts-converted"/>
<package name="xorg-x11-fonts-core"/>
<package name="xorg-x11-fonts-legacy"/>
<package name="xorg-x11-libX11-ccache"/>
<package name="xorg-x11-libs"/>
<package name="xorg-x11-server"/>
<package name="xorg-x11-server-Xspice"/>
<package name="xorg-x11-server-extra"/>
<package name="xorg-x11-server-sdk"/>
<package name="xorg-x11-server-source"/>
<package name="xorg-x11-server-sdk"/>
<package name="xorg-x11-util-devel"/>
<package name="xrdp"/>
<package name="xorgxrdp"/>
<package name="xrandr"/>
<package name="yast2"/>
<package name="yast2-sysconfig"/>
<package name="yast2-online-update-configuration"/>
<package name="zenmap"/>
```

**Comment by schaefi** [comment] 2022-02-13 21:19
Hmm, I'm sorry I was not able to reproduce this issue. I can build example images for leap 15.3 and they don't show this particular error. There are also the integration tests in obs which do not expose an issue in this regard:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86:leap

Maybe you can double check your image description with one of those to see a difference.

```
KiwiCommandError: chroot: stderr: groupadd:
```

This message however points to some users setup in your image description which I don't see as you only posted the package list

**Comment by schaefi** [comment] 2022-03-18 20:30
I'm sorry I overlooked this to be still open, but I think after the long time this is open the issue could either be resolved with the information provided or is no longer of interest. I'm closing this one now, feel free to open a new issue if the problem still persists. Thanks

**Closed as completed by schaefi** 2022-03-18 20:30 UTC
